name: Deploy Website and Sync Data

on:
  push:
    branches: [master]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许写入仓库内容
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create data directory
        run: mkdir -p data

      - name: Check if text_collection.json exists
        id: check-file
        run: |
          if [ ! -f data/text_collection.json ]; then
            echo '[]' > data/text_collection.json
          fi

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/text_collection.json
          git commit -m "Auto-initialize text collection data" || exit 0
          git push
